version: '3.5'

services:
  app:
    build: .
    ports:
      - '8081:8080'
    depends_on:
      - postgres
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/app
  postgres:
    image: 'postgres:alpine'
    container_name: 'app-postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=app
